version: '3.8'

services:
  web:
    build:
      context: ./ournft_site
      dockerfile: Dockerfile.prod
    command: /env/bin/gunicorn ournft_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:1337
    depends_on:
      - web

volumes:
  db.sqlite3:
  static_volume:
  media_volume: