# Generated by Django 4.0.3 on 2022-03-07 14:47

from django.db import migrations, models
import ournft_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ournft_app', '0002_remove_image_title_image_image_hash_image_ouwner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=ournft_app.models.image_path),
        ),
    ]
